version: '3.8'

services:
  furutsu_db:
    container_name: furutsu_test_db
    image: postgres:12.4
    command: |
      postgres -c log_statement=all -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.max=10000 -c pg_stat_statements.track=all -c log_min_messages=DEBUG1
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: furutsu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres