import Vue from 'vue'
import Vuetify, {
    VApp,
    VAppBar,
    VContainer,
    VImg,
    VSpacer,
    VBtn,
    VIcon,
    VMain,
    VRow,
    VCol,
    VCard,
    VCardTitle,
    VCardText,
    VCardSubtitle,
    VCardActions,
    VMenu,
    VExpansionPanel,
    VExpansionPanelHeader,
    VExpansionPanels,
    VExpansionPanelContent,
    VDataTable,
    VList,
    VListItem,
    VListItemAvatar,
    VListItemTitle,
    VSheet,
    VForm,
    VDialog,
    VTextField,
    VEditDialog,
    VListItemSubtitle,
    VListItemContent,
    VChip,
    VSelect,
    VSubheader,
    VDivider,
    VSkeletonLoader
} from 'vuetify/lib'

Vue.use(Vuetify, {
    components: {
        VSkeletonLoader,
        VSubheader,
        VDivider,
        VSelect,
        VChip,
        VEditDialog,
        VListItemSubtitle,
        VListItemContent,
        VForm,
        VDialog,
        VTextField,
        VSheet,
        VApp,
        VAppBar,
        VContainer,
        VImg,
        VSpacer,
        VBtn,
        VIcon,
        VMain,
        VRow,
        VCol,
        VCard,
        VCardTitle,
        VCardText,
        VCardSubtitle,
        VCardActions,
        VMenu,
        VExpansionPanel,
        VExpansionPanelHeader,
        VExpansionPanels,
        VExpansionPanelContent,
        VDataTable,
        VList,
        VListItem,
        VListItemAvatar,
        VListItemTitle,
    }
})

export default new Vuetify({
    theme: {
        options: {
            customProperties: true,
        },
        themes: {
            light: {
                primary: '#ee44aa',
                secondary: '#424242',
                accent: '#82B1FF',
                error: '#FF5252',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FFC107'
            },
        },
    },
})
